/* eslint-disable @typescript-eslint/no-var-requires */
const { readFile, writeFile } = require('fs').promises

const header = `---
layout: layout.njk
---

[//]: # "autogenerated"

`

// eslint-disable-next-line @typescript-eslint/no-extra-semi
;(async () => {
  try {
    const readme = await readFile('./README.md')
    await writeFile('./src/index.md', header + readme)
  } catch (err) {
    console.error('error', err)
  }
})()
